name: savely
description: With Savely, you can easily download and  retrieve the duration and type of a video, get the direct link of its thumbnail, and perform other operations .
version: 0.0.4
homepage: https://github.com/dj-yacine-flutter/Savely

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  test: ^1.24.2
